# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e83952c141342041108f85a70696214e41f5bec9aae68a59e9920047d2fb437fd465d0e3a67272f8516469c6bc8feda7b92506c0648b82a137a877bd58c421

test:
  secret_key_base: 9bee390ac99bfb73682777bb0e7093a915ddcf9448e2d4d275a99377cd86cb1a0b64593d6a16e82c2a553a13dc72fde4e55e806487fd5d91d5f8915e4dfd30b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9bee390ac99bfb73682777bb0e7093a915ddcf9448e2d4d275a99377cd86cb1a0b64593d6a16e82c2a553a13dc72fde4e55e806487fd5d91d5f8915e4dfd30b3
